version: '3'

services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:${APP_WEBROOT}
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - php-fpm
    networks:
      - magento
    restart: always

  php-fpm:
    container_name: php-fpm
    hostname: php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:${DOC_ROOT}
      - ./src:${APP_WEBROOT}
      - ./php.ini:/usr/local/etc/php/conf.d/my-custom-php.ini
      - ./.env:${DOC_ROOT}/local-environment
    depends_on:
      - db
      - elasticsearch
      - mailhog
      - redis
      - rabbitmq
    networks:
      - magento

  db:
    container_name: mariadb
    hostname: db
    image: mariadb:${MARIADB_VERSION}
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - magento

  redis:
    container_name: redis
    hostname: redis
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379
    depends_on:
      - db
    networks:
      - magento

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - magento

  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    entrypoint: /usr/share/elasticsearch/es-plugins.sh
    ports:
      - 9200:9200
    depends_on:
      - db
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - ./es-plugins.sh:/usr/share/elasticsearch/es-plugins.sh
      - es_data:/usr/share/elasticsearch/data
    networks:
      - magento

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - db
    networks:
      - magento

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - magento

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - magento

networks:
  magento:
    driver: bridge

volumes:
  db_data:
  es_data: